services:
  db:
    image: mariadb:10.6.9-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
      - 33060
    networks:
      - wordpress-network

  wp:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
    volumes:
      - wp_data:/var/www/html:rw
      - ./configuration/apache2.conf:/etc/apache2/apache2.conf:ro
    networks:
      - wordpress-network

  cli:
    depends_on: 
      - db
      - wp
    image: wordpress:cli    
    env_file: .env
    # This is required to run wp-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
    environment:
      WP_CLI_CACHE_DIR: ${WP_CLI_CACHE_DIR}
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wp_data:/var/www/html:rw
      - ./bin/install-wp.sh:/usr/local/bin/install-wp:ro
    networks:
      - wordpress-network

volumes:
  db_data:
  wp_data:

networks:
  wordpress-network:
    driver: bridge
