services:
  db:
    image: mariadb:10.6.9-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=notroot
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=funktionst
      - MYSQL_PASSWORD=janster
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=funktionst
      - WORDPRESS_DB_PASSWORD=janster
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
